# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

source 'https://git.coding.net/aRash/FMbase.git'

target 'FM' do
   use_frameworks!
   pod 'FMbase'

  # Pods for FM

end
